'use strict';
const crypto=require('node:crypto');
function fail(m){const e=new Error(m);e.statusCode=422;throw e;} function req(v,f,n=255){if(typeof v!=='string'||!v.trim())fail(`${f} is required`);if(v.trim().length>n)fail(`${f} too long`);return v.trim();}
function digest(v,f){const x=req(v,f,64).toLowerCase();if(!/^[a-f0-9]{64}$/.test(x))fail(`${f} must be a SHA-256 digest`);return x;}
function normalize(input={},now=new Date()){
 const capturedAt=new Date(input.capturedAt);if(Number.isNaN(capturedAt.getTime())||capturedAt>new Date(now.getTime()+300000))fail('capturedAt is invalid');
 const lat=Number(input.latitude),lon=Number(input.longitude),acc=Number(input.accuracyM);if(!Number.isFinite(lat)||lat< -90||lat>90||!Number.isFinite(lon)||lon< -180||lon>180||!Number.isFinite(acc)||acc<0||acc>1000)fail('coordinates or accuracyM are invalid');
 const species=req(input.speciesTaxon,'speciesTaxon',160),health=req(input.healthClass,'healthClass',30);if(!['healthy','stressed','bleached','diseased','unknown'].includes(health))fail('healthClass is invalid');
 const survival=req(input.survivalStatus,'survivalStatus',20);if(!['alive','dead','unknown'].includes(survival))fail('survivalStatus is invalid');
 const initial=input.initialSizeCm==null?null:Number(input.initialSizeCm),current=input.currentSizeCm==null?null:Number(input.currentSizeCm);if(initial!=null&&(!Number.isFinite(initial)||initial<=0))fail('initialSizeCm is invalid');if(current!=null&&(!Number.isFinite(current)||current<0))fail('currentSizeCm is invalid');if((initial==null||current==null)&&!String(input.missingReason||'').trim())fail('missingReason is required for missing size data');
 return {siteKey:req(input.siteKey,'siteKey',80),colonyKey:req(input.colonyKey,'colonyKey',80),interventionType:req(input.interventionType,'interventionType',80),surveyId:req(input.surveyId,'surveyId',120),sourceRecordId:req(input.sourceRecordId,'sourceRecordId',160),sourceSha256:digest(input.sourceSha256,'sourceSha256'),imageSha256:digest(input.imageSha256,'imageSha256'),datasetVersion:req(input.datasetVersion,'datasetVersion',80),modelVersion:req(input.modelVersion,'modelVersion',80),deviceId:req(input.deviceId,'deviceId',120),speciesTaxon:species,healthClass:health,survivalStatus:survival,initialSizeCm:initial,currentSizeCm:current,growthCm:initial!=null&&current!=null?Number((current-initial).toFixed(3)):null,missingReason:String(input.missingReason||'').trim()||null,latitude:lat,longitude:lon,accuracyM:acc,capturedAt,season:req(input.season,'season',40)};
}
function evaluate(cases){if(!Array.isArray(cases)||!cases.length)fail('cases must be non-empty');let species=0,health=0,review=0;for(const r of cases){for(const f of ['speciesCorrect','healthCorrect','scientistAccepted'])if(typeof r[f]!=='boolean')fail(`boolean ${f} required`);species+=r.speciesCorrect;health+=r.healthCorrect;review+=r.scientistAccepted;}return{cases:cases.length,speciesAccuracy:species/cases.length,healthAccuracy:health/cases.length,scientistAcceptanceRate:review/cases.length};}
function eventHash(prev,event){return crypto.createHash('sha256').update(`${prev||''}|${JSON.stringify(event)}`).digest('hex');}
module.exports={normalize,evaluate,eventHash};
