'use strict';
const express=require('express');const pool=require('../config/database');const w=require('../services/fieldworkWorkflow');const router=express.Router();
const actor=req=>({id:Number(req.user.id),tenantId:req.user.tenant_id,role:req.user.role});function role(u,rs){if(!rs.includes(u.role)){const e=new Error(`requires ${rs.join(',')}`);e.statusCode=403;throw e;}}
async function tx(fn){const c=await pool.connect();try{await c.query('BEGIN');const r=await fn(c);await c.query('COMMIT');return r;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
async function event(c,u,id,type,payload){await c.query('SELECT pg_advisory_xact_lock(hashtext($1))',[u.tenantId]);const prev=(await c.query('SELECT event_hash FROM fieldwork_events WHERE tenant_id=$1 ORDER BY id DESC LIMIT 1',[u.tenantId])).rows[0]?.event_hash||null;const value={observationId:id,type,actorId:u.id,payload,occurredAt:new Date().toISOString()};await c.query('INSERT INTO fieldwork_events(tenant_id,observation_id,event_type,actor_user_id,payload,previous_hash,event_hash) VALUES($1,$2,$3,$4,$5,$6,$7)',[u.tenantId,id,type,u.id,value,prev,w.eventHash(prev,value)]);}
router.post('/observations',async(req,res,next)=>{try{const u=actor(req);role(u,['scientist','admin']);const v=w.normalize(req.body);const row=await tx(async c=>{const r=(await c.query(`INSERT INTO governed_field_observations(tenant_id,site_key,colony_key,intervention_type,survey_id,source_record_id,source_sha256,image_sha256,dataset_version,model_version,device_id,species_taxon,health_class,survival_status,initial_size_cm,current_size_cm,growth_cm,missing_reason,latitude,longitude,accuracy_m,captured_at,received_at,season,collected_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,NOW(),$23,$24) ON CONFLICT(tenant_id,source_record_id) DO NOTHING RETURNING *`,[u.tenantId,v.siteKey,v.colonyKey,v.interventionType,v.surveyId,v.sourceRecordId,v.sourceSha256,v.imageSha256,v.datasetVersion,v.modelVersion,v.deviceId,v.speciesTaxon,v.healthClass,v.survivalStatus,v.initialSizeCm,v.currentSizeCm,v.growthCm,v.missingReason,v.latitude,v.longitude,v.accuracyM,v.capturedAt,v.season,u.id])).rows[0];if(!r){const e=new Error('sourceRecordId already synchronized');e.statusCode=409;throw e;}await event(c,u,r.id,'observation.recorded',v);return r;});res.status(201).json(row);}catch(e){next(e);}});
router.post('/observations/:id/reviews',async(req,res,next)=>{try{const u=actor(req);role(u,['scientist','admin']);const decision=String(req.body.decision||'');const rationale=String(req.body.rationale||'').trim();if(!['accepted','rejected'].includes(decision)||rationale.length<10)return res.status(422).json({error:'accepted/rejected decision and 10+ character rationale required'});const row=await tx(async c=>{const o=(await c.query('SELECT * FROM governed_field_observations WHERE id=$1 AND tenant_id=$2 FOR UPDATE',[req.params.id,u.tenantId])).rows[0];if(!o)return null;if(Number(o.collected_by)===u.id){const e=new Error('scientist review must be independent from collector');e.statusCode=403;throw e;}const r=(await c.query('INSERT INTO fieldwork_scientist_reviews(tenant_id,observation_id,decision,rationale,reviewer_user_id) VALUES($1,$2,$3,$4,$5) RETURNING *',[u.tenantId,o.id,decision,rationale,u.id])).rows[0];await c.query('UPDATE governed_field_observations SET review_status=$1 WHERE id=$2',[decision,o.id]);await event(c,u,o.id,`review.${decision}`,{reviewId:r.id,rationale});return r;});if(!row)return res.status(404).json({error:'observation_not_found'});res.status(201).json(row);}catch(e){next(e);}});
router.post('/evaluations',(req,res,next)=>{try{role(actor(req),['scientist','admin']);res.json(w.evaluate(req.body.cases));}catch(e){next(e);}});
router.get('/observations/:id',async(req,res,next)=>{try{const u=actor(req);const o=(await pool.query('SELECT * FROM governed_field_observations WHERE id=$1 AND tenant_id=$2',[req.params.id,u.tenantId])).rows[0];if(!o)return res.status(404).json({error:'observation_not_found'});const [reviews,events]=await Promise.all([pool.query('SELECT * FROM fieldwork_scientist_reviews WHERE observation_id=$1 AND tenant_id=$2 ORDER BY id',[o.id,u.tenantId]),pool.query('SELECT * FROM fieldwork_events WHERE observation_id=$1 AND tenant_id=$2 ORDER BY id',[o.id,u.tenantId])]);res.json({observation:o,reviews:reviews.rows,events:events.rows});}catch(e){next(e);}});
router.use((e,req,res,next)=>{if(res.headersSent)return next(e);console.error('[fieldwork]',e.message);res.status(e.statusCode||500).json({error:e.statusCode?e.message:'fieldwork_failed'});});module.exports=router;
